import { Property } from './property';

export const PROPERTIES: Property[] = [
  { id: 1, address: '123 Road Street',
    acType: 'Central Heat/Air',
    city: 'Andalusia',
    hasDishwasher: true,
    hasStove: true,
    hasRefrigerator: true,
    noBeds: 3,
    noFullBaths: 3,
    noHalfBaths: 3,
    sqft: 1000,
    depositPrice: 600,
    rentPrice: 600,
    comments: 'Fenced Yard'},
  { id: 1, address: '14 Avenue Street',
    acType: 'Central Heat/Air',
    city: 'Andalusia',
    hasDishwasher: true,
    hasStove: true,
    hasRefrigerator: true,
    noBeds: 3,
    noFullBaths: 3,
    noHalfBaths: 3,
    sqft: 1000,
    depositPrice: 600,
    rentPrice: 600,
    comments: 'Fenced Yard'},
  { id: 1, address: '143 Poo Road',
    acType: 'Central Heat/Air',
    city: 'Andalusia',
    hasDishwasher: true,
    hasStove: true,
    hasRefrigerator: true,
    noBeds: 3,
    noFullBaths: 3,
    noHalfBaths: 3,
    sqft: 1000,
    depositPrice: 600,
    rentPrice: 600,
    comments: 'Fenced Yard'},
  { id: 1, address: '44 Ghetto Avenue',
    acType: 'Central Heat/Air',
    city: 'Andalusia',
    hasDishwasher: true,
    hasStove: true,
    hasRefrigerator: true,
    noBeds: 3,
    noFullBaths: 3,
    noHalfBaths: 3,
    sqft: 1000,
    depositPrice: 600,
    rentPrice: 600,
    comments: 'Fenced Yard'},
]
